### ISSUE TITLE
Documentation is missing?

### ISSUE THREAD

**Issue by maksimdrachov** [Zubax/dronecode_probe#11]
If I click in the README on:

<img width="796" alt="image" src="https://github.com/user-attachments/assets/4a58c911-0c75-4ced-b3a7-4f1395536208">

I get to:

<img width="1166" alt="image" src="https://github.com/user-attachments/assets/e1a57e00-e801-43b1-8674-cba8b7a67934">

(which refers me back to the same github repository)

**Comment by pavel-kirienko** [comment]
Will be fixed in https://github.com/Zubax/dronecode_probe/pull/9 once I have time to review it
